import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const description = metadata.description ?? '';
    const title = metadata.title?.toString() ?? '';
    return (
        <html lang="en">
            <Head>
                <title>{title}</title>
                <meta name="description" content={description} />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <body className={inter.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
